services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - BACKEND_API_URL=http://backend:3000/api
      - PORT=5173
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - FRONTEND_URL=http://frontend:5173
      - BALL_DONT_LIE_API_KEY=${BALL_DONT_LIE_API_KEY}
    volumes:
      - ./backend:/app
      - ./backend/database:/app/database
    networks:
      - app-network
  backend-test:
    build: ./backend
    environment:
      - PORT=3000
      - FRONTEND_URL=http://frontend:5173
      - BALL_DONT_LIE_API_KEY=${BALL_DONT_LIE_API_KEY}
      - NODE_ENV=test
    volumes:
      - ./backend:/app
    command: ["npm", "run", "test"]
    networks:
      - app-network
networks:
  app-network:
    driver: bridge